### ISSUE TITLE
Maybe get_key should go here

### ISSUE THREAD

**Issue by clozinski** [Cromlech/cromlech.jwt#1]
Well it looks like you did move the jwt stuff out of the crom demo. 
Thank you. 

Maybe get_key should also be moved here.  Code is appended. 

I am a bit surprised at myself for being so anal retentive about this clean up stuff.  
And then I realized why.  There really is a huge amount of stuff going on here.  I found myself
literally rereading the documentation I wrote last night to better understand what is going on. 
And then I started digging in a layer deeper. So anything I can push out of my way
makes my thinking clearer, makes the understanding easier. 

You were quite modest about your accomplishments.  But really there are a lot of ideas
and abstractions floating around here.  While Grok is complex, in that it is a big tangle (I did not realize 
how bad a tangle it was until I started studying Cromlech), Cromlech is also complex in that it is a rich
set of abstractions.  So whatever we can do to simplify it is useful.  Moving JWT out was a great step. 
move out get_key.  Move out Sessiond.  

As for me, I continue to read and reread the code, each time going one layer deeper.  I am making progress. 

Here is a copy of the code
```
def get_key(path):
    """ This either loads the encryption key from a file, or                    
    generates a new key                                                         
    """
    from cromlech.jwt.components import JWTHandler
    if not os.path.isfile(path):
        with open(path, 'w+', encoding="utf-8") as keyfile:
            key = JWTHandler.generate_key()
            export = key.export()
            keyfile.write(export)
    else:
        key = JWTHandler.load_key_file(path)
    return key
```

**Comment by trollfot** [comment]
Part of it was moved in.
The part where the file is opened is not, because it's an implementation detail.
See tests for more usage.
