### ISSUE TITLE
Needs a self argument

### ISSUE THREAD

**Issue by PythonLinks** [Cromlech/cromlech.jwt#2]
https://github.com/Cromlech/cromlech.jwt/blob/master/src/cromlech/jwt/components.py#L53

```
   def load_key_file(path):
   ...
        return self.load_key_string(keystr)
```
In the return there is a self argument, but you did not pass it. 

Once I fixed that all seemed to work fine.

**Comment by trollfot** [comment]
Fixed.
The methods were a bit changed.
See the tests for more info.

**Comment by PythonLinks** [comment]
> On Dec 20, 2017, at 8:24 PM, Souheil Chelfouh <notifications@github.com> wrote:
> 
> See the tests for more info.

I will just use it.  If it works, I am a happy man.  

As for your arms.  That is a hugely serious issue.  I know a lot about this because I have had all of these problems. 

Including vision problems run your monitor in reverse video. 

Is it carpel tunnel syndrome.  Get yourself a microsoft ergonomic keyboard. 

Does your back or neck hurt?  If so I will tell you what to do about that as well.

I really can’t have other grok and cromlech die under me. 

And the cromlech icon is brilliant.   Do you have a larger version of that?

Warm Regards
Christopher Lozinski

https://PythonLinks.info
tel: +48 12 361 3136
Skype: clozinski
